export const ADD_ARTICLE_TO_LIST="ADD_ARTICLE_TO_LIST";
export const DELETE_ARTICLE_FROM_LIST="DELETE_ARTICLE_FROM_LIST";
export const MODIFY_ARTICLE_FROM_LIST ="MODIFY_ARTICLE_FROM_LIST";
export const GET_ARTICLES_FROM_SERVER = "GET_ARTICLES_FROM_SERVER";
export const ERROR_REQUEST = "ERROR_REQUEST";
export const LOAD_SUCCES = "LOAD_SUCCES";
export const LOAD_REQUEST = "LOAD_REQUEST";
export const EDIT_ARTICLE = "EDIT_ARTICLE";